### ISSUE TITLE
layout breaks when at certain breakpoints

### ISSUE THREAD

**Issue by neptunian** [neptunian/react-photo-gallery#60]
caused by browser returning the containing element of gallery's width as for example 1200px when its actually 1199.5px in the computed output.  since i cannot force it to round down before it is returned to me i subtract one pixel for prevention.

**Comment by louisdvs** [comment]
Hey, 
Thanks for the awesome component!
I'm still getting this issue with the current version have you pushed your fix to npm?
Cheers

**Comment by neptunian** [comment]
@louisdvs i published a new release

**Comment by louisdvs** [comment]
@neptunian thanks, my layout was still breaking at certain widths (updated to 5.6.2), I changed the value from 1 to 2 and it's not breaking anymore.
```
// subtract 1 pixel because the browser may round up a pixel
const containerWidth = this.state.containerWidth - 2;
```

Cheers

**Comment by marko911** [comment]
This is still an issue, in IE 11. I've updated to 5.6.2, I also tried changing containerWidth to 2, 3, even 5 but still doesn't make a difference. The columns still break at certain breakpoints and I end up having one image in a row instead of 3 , and then the other 2 on the next row. @neptunian

**Comment by neptunian** [comment]
@marko911 are you not able to update to the very latest version?

**Comment by marko911** [comment]
@neptunian I did update successfully but the problem persists in IE 11. Its fixed in chrome yes but not IE.

**Comment by neptunian** [comment]
@marko911 okay i'll look into it, thank you

**Comment by marko911** [comment]
any updates on this @neptunian ?

**Comment by neptunian** [comment]
@marko911 i tested in IE11 at various breakpoints and could not get the layout to "break".  Did you mess with the CSS at all of the images in an external stylesheet?

**Comment by marko911** [comment]
@neptunian no I didn't change any css , but  here check out how it breaks where I use it maybe its something else I didn't think of (scroll to collection) :  [LINK](http://ec2-34-212-100-177.us-west-2.compute.amazonaws.com/)

**Comment by neptunian** [comment]
did you try updating to version 6?

**Comment by marko911** [comment]
Hi, Yes, but still breaking. I've taken my images and properties and ported them into your demo and they don't break in the demo so I am trying to investigate now why it is breaking in my app. Thanks for follow up. @neptunian

**Comment by neptunian** [comment]
let me know if you can't find a solution.  right now the image sizes are calculated down to fractions of a pixel. it makes it so everything looks very even, but i think i can round it down a bit to leave some "safe space" when things are a bit off for whatever reason.

**Comment by marko911** [comment]
@neptunian You can close this. I've resolved the issue using the new version and a custom image component. There are no issues with your code , thanks for support :)

**Comment by neptunian** [comment]
okay cool, well i published a new release anyway getting rid of some decimals that might have helped :)
